---
development:
  cloud_name: evolcucorp
  api_key: '541385194626716'
  api_secret: MKq9bafpKoTW_VIYzXGrcPMV16E
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: evolcucorp
  api_key: '541385194626716'
  api_secret: MKq9bafpKoTW_VIYzXGrcPMV16E
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: evolcucorp
  api_key: '541385194626716'
  api_secret: MKq9bafpKoTW_VIYzXGrcPMV16E
  enhance_image_tag: true
  static_image_support: false
